---

exclude:
  - vendor/*
  - node_modules/*

linters:
  LineLength:
    max: 180
  
  RuboCop:
    enabled: true
    ignored_cops:
      - Layout/TrailingEmptyLines
      - Layout/HashAlignment
      - Style/FrozenStringLiteralComment
      - Layout/IndentationWidth
      - Lint/Void
      - Style/Next