databases:
  - name: rails-project-64-corporate-blog
    databaseName: rails-project-64-corporate-blog
    user: rails-project-64-corporate-blog
    plan: free

services:
  - type: web
    name: rails-project-64-corporate-blog
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-project-64-corporate-blog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
