default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/digibash_development.sqlite3

test:
  <<: *default
  database: db/digibash_test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: digibash_production
  username: digibash
  password: <%= ENV["RAILS_PROJECT_64_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
