default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/rails_project_64_development.sqlite3

test:
  <<: *default
  database: db/rails_project_64_test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: rails_project_64_production
  username: rails_project_64
  password: <%= ENV["RAILS_PROJECT_64_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
